---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
game_sales <- CodeClanData::game_sales
```


```{r}
games <- sort(unique(game_sales$name))
year <- sort(unique(game_sales$year_of_release))
platform <- sort(unique(game_sales$platform))
publisher <- sort(unique(game_sales$publisher))
genre <- sort(unique(game_sales$genre))
rating <- sort(unique(game_sales$rating))

```


```{r}

game_sales %>% 
  select(platform, sales, year_of_release) %>% 
  group_by(year_of_release) %>% 
  summarise(total_sales = sum(sales)) %>% 
  ungroup() %>% 
  ggplot() + 
  aes(x = year_of_release, y = total_sales) +
  geom_line(linetype = "dashed") +
  geom_point(size = 4, shape = 22, colour = "darkred", fill = "pink") +
  labs(x = "Year", y = "Total Sales", title = "Total Game Sales Year on Year")
  


```

```{r}
game_sales %>% 
  ggplot() +
  aes(x = user_score, y = critic_score, colour = publisher) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
game_sales %>% 
  ggplot() +
  aes(x = platform ) +
  geom_histogram(aes(y=..density..), bins = 20, colour="black", fill="white")+
  geom_density(alpha=.2, fill="#FF6666")

game_sales %>% 
    ggplot() +
      aes(x = name, y = sales) +
      geom_col(fill = "#ff1493") +
      theme(legend.position = "none") +
      coord_flip() +
      scale_y_continuous(breaks = seq(1,10)) +
      labs(x = "Game Title", y = "Sales")

```

```{r}
game_sales
```

